### PR TITLE
bump react 18, render to root container, vite plugin version

### LINKED ISSUE #1: Upgrade to a latest react

### PR DESCRIPTION
**Pull request by lksei**
template looks useful, let's bump react to keep on track (=

btw need to update vite react plugin, but firstly needed update vite itself

closes #1

### CODE REVIEW

**Comment by alexey-pd** [comment]
closes #1

**Comment by lksei** [comment]
fresh vite react here https://github.com/effector/vite-react-template/pull/6

**Comment by sergeysova** [comment]
@alexey-pd Please, solve conflicts.
Thank you for contribution!

**Comment by lksei** [comment]
got it @sergeysova now must be ok

move vite update here too for simplify flow for https://github.com/effector/vite-react-template/issues/1 and https://github.com/effector/vite-react-template/issues/2

**Pull request merged**
